
spring:
  application:
    name : rabbitmq
  rabbitmq:
    publisher-confirms: true
    virtual-host: /
    host: 192.168.159.128
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
server:
  port: 8084

